### ISSUE TITLE
Unsynched video

### ISSUE THREAD

**Issue by 1Uncs** [mohad12211/twitch-downloader-gui#7]
Unsynched video caused by highest quality download audio and video are not synched sometimes they are other times have to use handbrake to take it to 30fps. Update on the fix?

**Comment by mohad12211** [comment]
can you please provide example of a video that was not synced properly?

**Comment by 1Uncs** [comment]
> 

https://www.twitch.tv/videos/1745394921

**Comment by 1Uncs** [comment]
any temporary fix?

**Comment by mohad12211** [comment]
probably something related to https://github.com/lay295/TwitchDownloader/issues/556 ?
I don't think this has anything to do with this GUI wrapper.
it looks like vlc has the audio desync but if I play the video in mpv it doesn't.
